stages:
  prepare:
    cmd: python src/data_prep.py
    deps:
      - data/raw
      - src/data_prep.py
    outs:
      - data/processed

  train:
    cmd: python -m src.train
    deps:
      - data/processed
      - src/train.py
      - src/model.py
    outs:
      - models/unet_model.h5
    metrics:
      - metrics.json
