train:
  batch_size: 1
  epochs: 15        # Increased 10x for a better learning curve
  learning_rate: 0.001  # Standard default for faster initial learning
  loss_function: sparse_categorical_crossentropy